apiVersion: v2
name: axonops
description: >
  This helm chart install AxonOps server, dashboard and the required dependencies ElasticSearch
  and Apache Cassandra. You may optionally enable or disable the dependencies by setting the
  the values in the global section.
  Please refer to the https://axonops.com/docs/installation/kubernetes/ for more information.
type: application
version: 0.11.0
appVersion: 1.16.0

dependencies:
- name: elasticsearch
  repository: https://helm.elastic.co
  version: "7.13.3"
  condition: global.elasticsearch.enabled # This condition controls the dependency
- name: cassandra
  repository: https://charts.bitnami.com/bitnami
  version: "12.1.3"
  condition: global.cassandra.enabled
