axon-server:
  elasticHost: http://axon-elastic:8200
  image:
    repository: digitalisdocker/axon-server
    tag: latest
    pullPolicy: IfNotPresent

axon-dash:
  image:
    repository: digitalisdocker/axon-dash
    tag: latest
    pullPolicy: IfNotPresent
