# Minimal example values file for AxonOps
global:
  cassandra:
    enabled: true
    dc: &dc axonops1
    clusterName: &clusterNameCassandra "axonops-cassandra"
  elasticsearch:
    enabled: true
    clusterName: &clusterNameElastic "axonops-elastic"

axon-server:
  image:
    repository: registry.axonops.com/axonops-public/axonops-docker/axon-server
    tag: latest
    pullPolicy: IfNotPresent

  # Configure the Elasticsearch endpoint if you are not using the default Elasticsearch deployment
  elasticHost: http://axonops-elastic-master:9200

  # dashboardUrl should be set to the publicly-accessible URL for the AxonOps Dashboard
  dashboardUrl: https://axonops.example.com

  # Configure an ingress for external agents to connect
  agentIngress:
    enabled: false
    className: nginx
    annotations: {}
    hosts:
      - host: axonops-agents.example.com

  # Configure resources for the AxonOps Server pod.
  # See https://docs.axonops.com/installation/kubernetes/ for some guidelines
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # AxonOps Server configuration
  config:
    # Configure the name of your organisation here. This must match the organisation name used in your license key.
    org_name: "example"
    # Enter your AxonOps license key here
    license_key: ""
    cassandra:
      # For better performance on large clusters, you can use a CQL store for the metrics.
      # To opt-in for CQL metrics storage, just specify at least one CQL host.
      # We do recommend to specify a NetworkTopologyStrategy for cql_keyspace_replication
      cql_hosts: []
      #  - 192.168.0.10:9042
      #  - 192.168.0.11:9042
      #cql_username: "cassandra" # (CQL_USERNAME)
      #cql_password: "cassandra" # (CQL_PASSWORD)
      #cql_local_dc: axonops1 # (CQL_LOCAL_DC)
      #cql_ssl: false # (CQL_SSL)
      #cql_skip_verify: false  # (CQL_SSL_SKIP_VERIFY)
      #cql_ca_file: /path/to/ca_file  # (CQL_CA_FILE)
      #cql_cert_file: /path/to/cert_file  # (CQL_CERT_FILE)
      #cql_key_file: /path/to/key_file  # (CQL_KEY_FILE)
      #cql_autocreate_tables: true # (CQL_AUTO_CREATE_TABLES) this will tell axon-server to automatically create the metrics tables (true is recommended)
      #cql_keyspace_replication: "{ 'class' : 'SimpleStrategy', 'replication_factor' : 1 }" # (CQL_KS_REPLICATION) keyspace replication for the metrics tables
      #cql_read_consistency: "LOCAL_ONE" # (CQL_READ_CONSISTENCY) #One of the following:  ANY, ONE, TWO, THREE, QUORUM, ALL, LOCAL_QUORUM, EACH_QUORUM, LOCAL_ONE
      #cql_write_consistency: "LOCAL_ONE" # (CQL_WRITE_CONSISTENCY) #One of the following:    ANY, ONE, TWO, THREE, QUORUM, ALL, LOCAL_QUORUM, EACH_QUORUM, LOCAL_ONE

axon-dash:
  image:
    repository: registry.axonops.com/axonops-public/axonops-docker/axon-dash
    tag: latest
    pullPolicy: IfNotPresent

  # The service to access the AxonOps dashboard
  # You may chose for the service to be of type LoadBalancer or NodePort
  # If you're going to use an Ingress, the option should be set to ClusterIP
  service:
    type: ClusterIP

  ingress:
    enabled: false
    className: nginx
    annotations: {}
    hosts:
      - host: axonops.example.com

  # Resource requests and limits for the dashboard pods.
  # The recommended values are shown here
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1500Mi

cassandra:
  fullnameOveride: *clusterNameCassandra
  clusterName: *clusterNameCassandra
  cluster:
    datacenter: *dc

  # Adjust the memory and cpu requirements to your deployment
  #
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  persistence:
    enabled: true
    storageClass: ""
    size: "20Gi"
    commitLogsize: "4Gi"

elasticsearch:
  fullnameOveride: *clusterNameElastic
  clusterName: *clusterNameElastic
  replicas: 1
  minimumMasterNodes: 1
  masterService: ""
  esConfig:
    elasticsearch.yml: |
      thread_pool.write.queue_size: 2000
  roles:
    master: "true"
    ingest: "true"
    data: "true"
    remote_cluster_client: "false"
    ml: "false"

  # Adjust the memory and cpu requirements to your deployment
  esJavaOpts: "-Xms512M -Xmx512M"
  resources:
    requests:
      cpu: "1000m"
      memory: "1024Mi"
    limits:
      cpu: "2000m"
      memory: "1Gi"

  # If you want to use persistent storage, set enabled to true
  persistence:
    enabled: true

  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "" # adjust to your storageClass if you don't want to use default
    resources:
      requests:
        storage: 10Gi
