axon-server:
  elastic_host: http://axon-elastic
  image:
    repository: digitalisdocker/axon-server
    tag: latest
    pullPolicy: IfNotPresent

axon-dash:
  image:
    repository: digitalisdocker/axon-dash
    tag: latest
    pullPolicy: IfNotPresent
