apiVersion: v2
name: axon-server
description: Install AxonOps server
home: https://axonops.com
icon: https://static.wixstatic.com/media/a5611a_ade5ecd5de154e5381d2e13067f1aec3~mv2.png/v1/fill/w_163,h_47,al_c,usm_1.20_1.00_0.01,enc_auto/tr_logo.png
maintainers:
  - name: Sergio Rua
    email: sergio.rua@digitalis.io
    url: https://axonops.com
  - name: Richard Gooding
    email: richard@axonops.com
    url: https://axonops.com
type: application
version: 0.8.2
appVersion: 1.0.5
