apiVersion: v1
kind: Service
metadata:
  name: {{ template "axon-server.name" . }}-agent
  labels:
    {{- include "axon-server.labels" . | nindent 4 }}
{{- if .Values.agentService.labels }}
{{ toYaml .Values.agentService.labels | indent 4 }}
{{- end }}
{{- with .Values.agentService.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if (or (eq .Values.agentService.type "ClusterIP") (empty .Values.agentService.type)) }}
  type: ClusterIP
  {{- if .Values.agentService.clusterIP }}
  clusterIP: {{ .Values.agentService.clusterIP }}
  {{end}}
{{- else if eq .Values.agentService.type "LoadBalancer" }}
  type: {{ .Values.agentService.type }}
  {{- if .Values.agentService.loadBalancerIP }}
  loadBalancerIP: {{ .Values.agentService.loadBalancerIP }}
  {{- end }}
  {{- if .Values.agentService.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.agentService.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.agentService.type }}
{{- end }}
{{- if .Values.agentService.externalIPs }}
  externalIPs:
{{ toYaml .Values.agentService.externalIPs | indent 4 }}
{{- end }}
  ports:
    - name: agents
      port: {{ .Values.agentService.listenPort }}
      protocol: TCP
      targetPort: {{ .Values.config.listener.agents_port }}
{{ if (and (eq .Values.agentService.type "NodePort") (not (empty .Values.agentService.nodePort))) }}
      nodePort: {{.Values.agentService.nodePort}}
{{ end }}
  {{- if .Values.extraExposePorts }}
  {{- tpl (toYaml .Values.extraExposePorts) . | indent 4 }}
  {{- end }}
  selector:
    {{- include "axon-server.selectorLabels" . | nindent 4 }}
