{{- if .Values.agentIngress.enabled -}}
{{- $name := include "axon-server.name" . -}}
{{- $fullName := (print $name "-agent") }}
{{- $svcPort := .Values.agentService.listenPort -}}
{{- if and .Values.agentIngress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.agentIngress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.agentIngress.annotations "kubernetes.io/ingress.class" .Values.agentIngress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "axon-server.labels" . | nindent 4 }}
  {{- with .Values.agentIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.agentIngress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.agentIngress.className }}
  {{- end }}
  {{- if .Values.agentIngress.tls }}
  tls:
    {{- range .Values.agentIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.agentIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ default .path "/" }}
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: {{ default .pathType "Prefix" }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
    {{- end }}
{{- end }}
