apiVersion: v1
kind: Service
metadata:
  name: {{ include "axon-server.fullname" . }}
  labels:
    {{- include "axon-server.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "axon-server.selectorLabels" . | nindent 4 }}  
  ports:
    - protocol: TCP
      name: agent
      port: 1888
      targetPort: 1888
    - protocol: TCP
      name: api
      port: 8080
      targetPort: 8080
