apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "axon-server.fullname" . }}
  labels:
    {{- include "axon-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "axon-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "axon-server.selectorLabels" . | nindent 8 }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
  {{- if .Values.deployment.annotations }}
  {{ toYaml .Values.deployment.annotations }}
  {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "axon-server.serviceAccountName" . }}
      containers:
        - name: axon-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command: ["/bin/sh", "-c", "mkdir -p /var/log/axonops && /usr/share/axonops/axon-server -o std"]
          ports:
            - name: api
              containerPort: 8080
            - name: agent
              containerPort: 1888
          volumeMounts:
            - name: config
              mountPath: /etc/axonops
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
      volumes:
        - name: config
          configMap:
            name: {{ include "axon-server.fullname" . }}