apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "axon-server.fullname" . }}
  labels:
    {{- include "axon-server.labels" . | nindent 4 }}
data:
  axon-server.yml: |
{{ toYaml .Values.config.listener | indent 4 }}

    elastic_hosts:
      - {{ .Values.elasticHost }}

    org_name: {{ .Values.config.org_name }}
    license_key: {{ .Values.config.license_key }}

    axon_dash_url: {{ .Values.dashboardUrl }}

    # log_file: /dev/stdout

    alerting:
{{ toYaml .Values.config.alerting | indent 6 }}

    tls:
{{ toYaml .Values.config.tls | indent 6 }}

    auth:
{{ toYaml .Values.config.auth | indent 6 }}

{{ if .Values.config.extraConfig }}
{{ toYaml .Values.config.extraConfig | indent 4 }}
{{ end }}
