{{- if and .Values.serviceAccount.create .Values.serviceAccount.createClusterRole -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: rbac.authorization.k8s.io/v1
{{- else -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end -}}
kind: ClusterRoleBinding
metadata:
  name: {{ include "axon-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "axon-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "axon-server.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "axon-server.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
