{{- if and .Values.serviceAccount.create .Values.serviceAccount.createClusterRole -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "axon-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "axon-server.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/metrics
  - pods
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
{{- end -}}
