apiVersion: v1
kind: Service
metadata:
  name: {{ include "axon-dash.fullname" . }}
  labels:
    {{- include "axon-dash.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "axon-dash.selectorLabels" . | nindent 4 }}  
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
