apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "axon-dash.fullname" . }}
  labels:
    {{- include "axon-dash.labels" . | nindent 4 }}
data:
  axon-dash.yml: |
    axon-dash:
{{ toYaml .Values.config.listener | indent 6 }}
{{- if .Values.config.extraConfig }}
{{ toYaml .Values.config.extraConfig | indent 6 }}
{{- end }}
    axon-server:
      private_endpoints: {{ .Values.config.axonServerUrl }}
      context_path: "{{ default "" .Values.config.contextPath }}"
