apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "axon-dash.fullname" . }}
  labels:
    {{- include "axon-dash.labels" . | nindent 4 }}
data:
  axon-dash.yml: |
    axon-dash:
      host: 0.0.0.0
      port: 3000
      line_charts_max_results: 256
    axon-server:
      private_endpoints: {{ .Values.axonServerUrl }}
      context_path: "{{ default "" .Values.serverContextPath }}"
