apiVersion: v1
kind: Service
metadata:
  name: {{ include "axon-dash.fullname" . }}
  labels:
    {{- include "axon-dash.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "axon-dash.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}  
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
{{ if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{.Values.service.nodePort}}
{{ end }}
