apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "axon-dash.fullname" . }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
{{- if eq .Values.istio.protocol "https" }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.istio.tls.credentialName }}
        minProtocolVersion: TLSV1_2
        maxProtocolVersion: TLSV1_3
{{ else }}
    - port:
        number: 80
        name: http
        protocol: HTTP
{{- end }}
      hosts:
        - {{.Values.global.customer}}.{{.Values.global.baseDomain}}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: {{ include "axon-dash.fullname" . }}
spec:
  gateways:
    - {{ include "axon-dash.fullname" . }}
  hosts:
    - {{.Values.global.customer}}.{{.Values.global.baseDomain}}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: axon-dash.{{.Values.global.namespace}}.svc.cluster.local
            port:
              number: 3000
          weight: 100
