{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "axon-dash.serviceAccountName" . }}
  labels:
{{ include "axon-dash.labels" . | nindent 4 }}
{{- end -}}
